markdown: rdiscount
pygments: true
permalink: /posts/:title.html
auto: true
rdiscount:
  extensions: [smart]

title: deercoder's Weblog
author:
  name: deercoder
  email: lllccc2009@gmail.com
  github: deercoder
  twitter: DearCodeLover

