# Site settings
title: Chang Liu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Chang Liu's(aka deercoder) research blog
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: deercoder

# Build settings
markdown: kramdown
